<a href="https://colab.research.google.com/github/sherzod3/week3-lab/blob/main/exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals Exercises

This notebook contains exercises based on the PyTorch Fundamentals tutorial. Each section corresponds to a topic from the original notebook. Complete the exercises by filling in the code cells where indicated.

## 1. Introduction to Tensors

### Exercise 1.1: Create a scalar tensor
Create a scalar tensor with the value 42 and print its value, number of dimensions (ndim), and shape.

In [ ]:
import torch

# Create a scalar tensor
scalar = torch.tensor(42)

# Print details
print(scalar)
print(f"Number of dimensions: {scalar.ndim}")
print(f"Shape: {scalar.shape}")

tensor(42)
Number of dimensions: 0
Shape: torch.Size([])


### Exercise 1.2: Create a vector tensor
Create a vector tensor with values [1, 2, 3, 4] and print its value, ndim, and shape.

In [ ]:
# TODO: Create a vector tensor
vector =

# Print details
print(vector)
print(f"Number of dimensions: {vector.ndim}")
print(f"Shape: {vector.shape}")

SyntaxError: invalid syntax (ipython-input-2951682181.py, line 2)

### Exercise 1.3: Create a matrix tensor
Create a 2x3 matrix tensor with values [[1, 2, 3], [4, 5, 6]] and print its details.

In [ ]:
import torch

# Create a matrix tensor (2D)
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])

# Print details
print(matrix)
print(f"Number of dimensions: {matrix.ndim}")
print(f"Shape: {matrix.shape}")

tensor([[1, 2, 3],
        [4, 5, 6]])
Number of dimensions: 2
Shape: torch.Size([2, 3])


### Exercise 1.4: Create a 3D tensor
Create a tensor of shape (2, 2, 2) with sequential values from 1 to 8 using torch.arange and reshape.

In [ ]:
import torch

tensor_3d = torch.tensor([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])

print(tensor_3d)
print(f"Number of dimensions: {tensor_3d.ndim}")
print(f"Shape: {tensor_3d.shape}")

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
Number of dimensions: 3
Shape: torch.Size([2, 2, 3])


## 2. Random Tensors

### Exercise 2.1: Create a random tensor
Create a random tensor of shape (4, 4) and print it along with its dtype.

In [ ]:
import torch

# Create random tensor
random_tensor = torch.rand(2, 3)

print(random_tensor)
print(f"Datatype: {random_tensor.dtype}")

tensor([[0.3325, 0.5192, 0.9499],
        [0.6983, 0.7582, 0.6976]])
Datatype: torch.float32


### Exercise 2.2: Create an image-sized random tensor
Create a random tensor of shape (3, 224, 224) simulating an image (channels, height, width).

In [ ]:
import torch

# Create image-sized random tensor (Channels, Height, Width)
image_tensor = torch.rand(3, 224, 224)

print(f"Shape: {image_tensor.shape}")

Shape: torch.Size([3, 224, 224])


## 3. Zeros and Ones

### Exercise 3.1: Create a tensor of zeros
Create a tensor of zeros with shape (5, 5).

In [ ]:
import torch

# Create zeros tensor
zeros = torch.zeros(2, 3)

print(zeros)
print(f"Shape: {zeros.shape}")

tensor([[0., 0., 0.],
        [0., 0., 0.]])
Shape: torch.Size([2, 3])


### Exercise 3.2: Create a tensor of ones like another tensor
Create a random tensor of shape (3, 3), then create a tensor of ones with the same shape using ones_like.

In [ ]:
import torch

random_tensor = torch.rand(3, 3)

# Create ones_like tensor
ones_like = torch.ones_like(random_tensor)

print("Random tensor:")
print(random_tensor)
print("\nOnes_like tensor:")
print(ones_like)

Random tensor:
tensor([[0.0601, 0.6149, 0.6961],
        [0.1214, 0.7251, 0.6852],
        [0.3721, 0.8550, 0.4080]])

Ones_like tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


## 4. Creating Ranges

### Exercise 4.1: Create a range tensor
Create a tensor with values from 0 to 20 with a step of 2 using torch.arange.

In [ ]:
import torch

# Create range tensor from 0 to 9
range_tensor = torch.arange(0, 10)

print(range_tensor)
print(f"Shape: {range_tensor.shape}")

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Shape: torch.Size([10])


## 5. Tensor Datatypes

### Exercise 5.1: Create tensors with specific dtypes
Create a tensor with values [1.0, 2.0, 3.0] using dtype=torch.float16 and another with dtype=torch.int64.

In [ ]:
import torch

# Create float16 tensor
float16_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float16)

# Create int64 tensor
int64_tensor = torch.tensor([1, 2, 3], dtype=torch.int64)

print("Float16 tensor:")
print(float16_tensor)
print(f"Datatype: {float16_tensor.dtype}\n")

print("Int64 tensor:")
print(int64_tensor)
print(f"Datatype: {int64_tensor.dtype}")

Float16 tensor:
tensor([1., 2., 3.], dtype=torch.float16)
Datatype: torch.float16

Int64 tensor:
tensor([1, 2, 3])
Datatype: torch.int64


### Exercise 5.2: Change dtype
Convert the float16_tensor to float32.

In [ ]:
import torch

import torch

# Original tensor (float16)
float16_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float16)

# Convert to float32
float32_tensor = float16_tensor.to(torch.float32)

print("Original tensor:")
print(float16_tensor)
print(f"Datatype: {float16_tensor.dtype}\n")

print("Converted tensor (float32):")
print(float32_tensor)
print(f"Datatype: {float32_tensor.dtype}")

Original tensor:
tensor([1., 2., 3.], dtype=torch.float16)
Datatype: torch.float16

Converted tensor (float32):
tensor([1., 2., 3.])
Datatype: torch.float32


## 6. Getting Information from Tensors

### Exercise 6.1: Print tensor info
Create a random tensor of shape (2, 3, 4) and print its shape, dtype, and device.

## 7. Manipulating Tensors (Basic Operations)

### Exercise 7.1: Perform basic operations
Create a tensor [10, 20, 30]. Add 5, subtract 10, multiply by 2, and divide by 10.

In [ ]:
import torch

tensor = torch.tensor([10, 20, 30])

# Add 5
added = tensor + 5

# Subtract 10
subtracted = tensor - 10

# Multiply by 2
multiplied = tensor * 2

# Divide by 10
divided = tensor / 10  # natija float bo'ladi

print("Original tensor:", tensor)
print("After adding 5:", added)
print("After subtracting 10:", subtracted)
print("After multiplying by 2:", multiplied)
print("After dividing by 10:", divided)

Original tensor: tensor([10, 20, 30])
After adding 5: tensor([15, 25, 35])
After subtracting 10: tensor([ 0, 10, 20])
After multiplying by 2: tensor([20, 40, 60])
After dividing by 10: tensor([1., 2., 3.])


### Exercise 7.2: Matrix multiplication
Create two tensors A (2x3) and B (3x2) with random values and perform matrix multiplication.

In [ ]:
import torch

# Create matrices A (2x3) and B (3x2)
A = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
B = torch.tensor([[7, 8],
                  [9, 10],
                  [11, 12]])

# Matrix multiplication using torch.mm
result_mm = torch.mm(A, B)

# Matrix multiplication using @ operator
result_at = A @ B

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nResult using torch.mm:")
print(result_mm)
print("\nResult using @ operator:")
print(result_at)

Matrix A:
tensor([[1, 2, 3],
        [4, 5, 6]])

Matrix B:
tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

Result using torch.mm:
tensor([[ 58,  64],
        [139, 154]])

Result using @ operator:
tensor([[ 58,  64],
        [139, 154]])


## 8. Tensor Aggregation

### Exercise 8.1: Find min, max, mean, sum
Create a tensor with values from 0 to 100 and find its min, max, mean, and sum.

In [ ]:
import torch

agg_tensor = torch.arange(0, 101)  # 0 dan 100 gacha

# Minimum
min_val = agg_tensor.min()

# Maximum
max_val = agg_tensor.max()

# Mean (cast to float for accurate division)
mean_val = agg_tensor.float().mean()

# Sum
sum_val = agg_tensor.sum()

print("Tensor:", agg_tensor)
print("Min:", min_val.item())
print("Max:", max_val.item())
print("Mean:", mean_val.item())
print("Sum:", sum_val.item())

Tensor: tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
         28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
         42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
         56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
         70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
         84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
         98,  99, 100])
Min: 0
Max: 100
Mean: 50.0
Sum: 5050


### Exercise 8.2: Argmin and argmax
Find the positions of the minimum and maximum values in the above tensor.

In [ ]:
import torch

agg_tensor = torch.tensor([10, 50, 30, 70, 20])

# Index of minimum value
min_index = agg_tensor.argmin()

# Index of maximum value
max_index = agg_tensor.argmax()

print("Tensor:", agg_tensor)
print("Index of min value:", min_index.item())
print("Index of max value:", max_index.item())

Tensor: tensor([10, 50, 30, 70, 20])
Index of min value: 0
Index of max value: 3


## 9. Reshaping, Stacking, Squeezing, Unsqueezing

### Exercise 9.1: Reshape a tensor
Create a tensor of shape (10,) and reshape it to (2, 5).

In [ ]:
import torch

reshape_tensor = torch.arange(10)  # tensor([0, 1, 2, ..., 9])

# Reshape to 2x5
reshaped = reshape_tensor.reshape(2, 5)

print("Original tensor:", reshape_tensor)
print("Reshaped tensor:")
print(reshaped)
print("Shape:", reshaped.shape)

Original tensor: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Reshaped tensor:
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
Shape: torch.Size([2, 5])


### Exercise 9.2: Stack tensors
Create two tensors of shape (2, 2) and stack them vertically and horizontally.

In [ ]:
import torch

tensor1 = torch.rand(2, 2)
tensor2 = torch.rand(2, 2)

# Stack vertically (along rows, dim=0)
vertical_stack = torch.cat((tensor1, tensor2), dim=0)

# Stack horizontally (along columns, dim=1)
horizontal_stack = torch.cat((tensor1, tensor2), dim=1)

print("Tensor 1:\n", tensor1)
print("\nTensor 2:\n", tensor2)
print("\nVertical stack (dim=0):\n", vertical_stack)
print("\nHorizontal stack (dim=1):\n", horizontal_stack)

Tensor 1:
 tensor([[0.7606, 0.2307],
        [0.3397, 0.2729]])

Tensor 2:
 tensor([[0.4020, 0.6579],
        [0.3664, 0.3237]])

Vertical stack (dim=0):
 tensor([[0.7606, 0.2307],
        [0.3397, 0.2729],
        [0.4020, 0.6579],
        [0.3664, 0.3237]])

Horizontal stack (dim=1):
 tensor([[0.7606, 0.2307, 0.4020, 0.6579],
        [0.3397, 0.2729, 0.3664, 0.3237]])


### Exercise 9.3: Squeeze and unsqueeze
Create a tensor of shape (1, 3, 1), squeeze it, then unsqueeze it back on dim=0.

In [ ]:
import torch

squeeze_tensor = torch.rand(1, 3, 1)

# Squeeze → 1 bo‘lgan o‘lchamlarni olib tashlash
squeezed = squeeze_tensor.squeeze()

# Unsqueeze → dim=0 ga yangi singleton dimension qo‘shish
unsqueezed = squeezed.unsqueeze(0)

print("Original tensor shape:", squeeze_tensor.shape)
print("After squeeze shape:", squeezed.shape)
print("After unsqueeze shape:", unsqueezed.shape)

Original tensor shape: torch.Size([1, 3, 1])
After squeeze shape: torch.Size([3])
After unsqueeze shape: torch.Size([1, 3])


### Exercise 9.4: Permute
Create an image tensor (3, 100, 100) and permute it to (100, 100, 3).

In [ ]:
import torch

image_tensor = torch.rand(3, 100, 100)  # (C, H, W)

# Permute to (H, W, C)
permuted = image_tensor.permute(1, 2, 0)

print("Original shape:", image_tensor.shape)
print("Permuted shape:", permuted.shape)

Original shape: torch.Size([3, 100, 100])
Permuted shape: torch.Size([100, 100, 3])


## 10. Indexing

### Exercise 10.1: Index into a tensor
Create a tensor [[[1,2,3],[4,5,6],[7,8,9]]] and index to get 5, then the entire second row.

In [ ]:
import torch

index_tensor = torch.tensor([[[1, 2, 3],
                              [4, 5, 6],
                              [7, 8, 9]]])

# Get the element 5
element_5 = index_tensor[0, 1, 1]  # batch=0, row=1, col=1

# Get the second row [4, 5, 6]
second_row = index_tensor[0, 1]    # batch=0, row=1

print("Element 5:", element_5.item())
print("Second row:", second_row)

Element 5: 5
Second row: tensor([4, 5, 6])


## 11. PyTorch and NumPy

### Exercise 11.1: NumPy to PyTorch
Create a NumPy array [1,2,3,4] and convert it to a PyTorch tensor.

In [ ]:
import numpy as np
import torch

numpy_array = np.array([1, 2, 3, 4])

# Convert to tensor
from_numpy = torch.from_numpy(numpy_array)

print("NumPy array:", numpy_array)
print("Converted tensor:", from_numpy)

NumPy array: [1 2 3 4]
Converted tensor: tensor([1, 2, 3, 4])


### Exercise 11.2: PyTorch to NumPy
Create a PyTorch tensor [5,6,7,8] and convert it to a NumPy array.

In [ ]:
import torch

pytorch_tensor = torch.tensor([5, 6, 7, 8])

# Convert to NumPy array
to_numpy = pytorch_tensor.numpy()

print("PyTorch tensor:", pytorch_tensor)
print("Converted NumPy array:", to_numpy)

PyTorch tensor: tensor([5, 6, 7, 8])
Converted NumPy array: [5 6 7 8]


## 12. Reproducibility

### Exercise 12.1: Set manual seed
Set the manual seed to 77 and create two random tensors of shape (2,2). Check if they are equal.

In [ ]:
import torch

# Set seed
torch.manual_seed(77)
rand1 = torch.rand(2, 2)

# Reset seed to same value for reproducibility
torch.manual_seed(77)
rand2 = torch.rand(2, 2)

# Check equality
print("Rand1:\n", rand1)
print("Rand2:\n", rand2)
print("Are they equal?\n", rand1 == rand2)

Rand1:
 tensor([[0.2919, 0.2857],
        [0.4021, 0.4645]])
Rand2:
 tensor([[0.2919, 0.2857],
        [0.4021, 0.4645]])
Are they equal?
 tensor([[True, True],
        [True, True]])


## 13. Running on GPUs

### Exercise 13.1: Check for GPU
Write code to check if CUDA is available and set the device accordingly.

In [ ]:
# TODO: Set device
device =

### Exercise 13.2: Move tensor to GPU
Create a tensor and move it to the GPU if available. Then move it back to CPU and convert to NumPy.

In [ ]:
import torch

gpu_tensor = torch.tensor([10, 20, 30])

# Check if GPU is available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Move tensor to GPU (or remain on CPU if no GPU)
gpu_tensor = gpu_tensor.to(device)

print("Tensor on device:", gpu_tensor, "Device:", gpu_tensor.device)

# Move back to CPU and convert to NumPy
cpu_numpy = gpu_tensor.cpu().numpy()

print("Back on CPU as NumPy array:", cpu_numpy)

Tensor on device: tensor([10, 20, 30]) Device: cpu
Back on CPU as NumPy array: [10 20 30]
